/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.vfbellaver.views;

import com.br.vfbellaver.Implements.InquilinoDaoImp;
import com.br.vfbellaver.models.Inquilino;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author vfbellaver
 */
public class CadastroInquilino extends javax.swing.JFrame {

    /**
     * Creates new form CadastroInquilino
     */
    public CadastroInquilino() {
        initComponents();
    }

    private void limparCampos(){
        nomeInquilino.setText("");
        cpfInquilino.setText("");
        rgInquilino.setText("");
        orgEmissorRgInquilino.setText("");
        telefoneInquilino.setText("");
        profissaoInquilino.setText("");
        nacionalidadeInquilino.setText("");
        enderecoInquilino.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rgInquilino = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        orgEmissorRgInquilino = new javax.swing.JTextField();
        cpfInquilino = new javax.swing.JTextField();
        nomeInquilino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        profissaoInquilino = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        enderecoInquilino = new javax.swing.JTextField();
        cancelarInquilinoBtn = new javax.swing.JToggleButton();
        salvarInquilinoBtn = new javax.swing.JButton();
        estadoCivilInquilino = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        nacionalidadeInquilino = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        telefoneInquilino = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/add_user.png"))); // NOI18N
        jLabel1.setText("Cadastro de Inquilinos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("RG:");

        rgInquilino.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rgInquilino.setMinimumSize(new java.awt.Dimension(160, 22));
        rgInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgInquilinoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Orgão Emissor:");

        orgEmissorRgInquilino.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        orgEmissorRgInquilino.setMinimumSize(new java.awt.Dimension(160, 22));
        orgEmissorRgInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgEmissorRgInquilinoActionPerformed(evt);
            }
        });

        cpfInquilino.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cpfInquilino.setMinimumSize(new java.awt.Dimension(160, 22));

        nomeInquilino.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nomeInquilino.setMinimumSize(new java.awt.Dimension(500, 22));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Profissão:");

        profissaoInquilino.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        profissaoInquilino.setMinimumSize(new java.awt.Dimension(500, 26));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Estado Civil:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Endereço:");

        enderecoInquilino.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        cancelarInquilinoBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelarInquilinoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/cancelar.png"))); // NOI18N
        cancelarInquilinoBtn.setText("Cancelar");
        cancelarInquilinoBtn.setPreferredSize(new java.awt.Dimension(150, 31));
        cancelarInquilinoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarInquilinoBtnActionPerformed(evt);
            }
        });

        salvarInquilinoBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salvarInquilinoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/visto.png"))); // NOI18N
        salvarInquilinoBtn.setText("Salvar");
        salvarInquilinoBtn.setPreferredSize(new java.awt.Dimension(150, 31));
        salvarInquilinoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarInquilinoBtnActionPerformed(evt);
            }
        });

        estadoCivilInquilino.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        estadoCivilInquilino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Divorciado" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Nacionalidade:");

        nacionalidadeInquilino.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Telefone:");

        telefoneInquilino.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        telefoneInquilino.setMinimumSize(new java.awt.Dimension(160, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelarInquilinoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salvarInquilinoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeInquilino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(profissaoInquilino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enderecoInquilino)
                                    .addComponent(estadoCivilInquilino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nacionalidadeInquilino)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cpfInquilino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(telefoneInquilino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rgInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orgEmissorRgInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cpfInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(telefoneInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rgInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(orgEmissorRgInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(profissaoInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(estadoCivilInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nacionalidadeInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(enderecoInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarInquilinoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salvarInquilinoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        jLabel9.getAccessibleContext().setAccessibleName("Endereço");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orgEmissorRgInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgEmissorRgInquilinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgEmissorRgInquilinoActionPerformed

    private void cancelarInquilinoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarInquilinoBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelarInquilinoBtnActionPerformed

    private void salvarInquilinoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarInquilinoBtnActionPerformed
        InquilinoDaoImp inqDaoImp = new InquilinoDaoImp();
        Inquilino inquilino = new Inquilino();
        
        if(nomeInquilino.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Informe o nome do inquilino.");
            nomeInquilino.requestFocus();
            return;
        }
        
        if(cpfInquilino.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Informe o CPF do inquilino.");
            nomeInquilino.requestFocus();
            return;
        }
        
        if(rgInquilino.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Informe o Rg do inquilino.");
            nomeInquilino.requestFocus();
            return;
        }
        
        if(orgEmissorRgInquilino.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Informe o orgão emissor do RG.");
            nomeInquilino.requestFocus();
            return;
        }
        
        if(profissaoInquilino.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Informe a profissão do inquilino.");
            nomeInquilino.requestFocus();
            return;
        }
        if(profissaoInquilino.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Informe o endereço do inquilino.");
            nomeInquilino.requestFocus();
            return;
        }
        else{
            inquilino = new Inquilino();
            inquilino.setNome(nomeInquilino.getText());
            inquilino.setCpf(Long.parseLong(cpfInquilino.getText()));
            inquilino.setRegistroGeral(Long.parseLong(rgInquilino.getText()));
            inquilino.setOrgaoEmissor(orgEmissorRgInquilino.getText());
            inquilino.setNacionalidade(nacionalidadeInquilino.getText());
            inquilino.setProfissao(profissaoInquilino.getText());
            inquilino.setTelefone(telefoneInquilino.getText());
            inquilino.setEndereco(enderecoInquilino.getText());
            
            try {
                inqDaoImp.persistir(inquilino);                
                JOptionPane.showMessageDialog(null, "Inquilino cadastrado com sucesso");
                 setVisible(false);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao salvar Inquilino. Erro = "+ex.getMessage());
            }
            
        }
    }//GEN-LAST:event_salvarInquilinoBtnActionPerformed

    private void rgInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgInquilinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgInquilinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroInquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroInquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroInquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroInquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroInquilino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cancelarInquilinoBtn;
    private javax.swing.JTextField cpfInquilino;
    private javax.swing.JTextField enderecoInquilino;
    private javax.swing.JComboBox<String> estadoCivilInquilino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nacionalidadeInquilino;
    private javax.swing.JTextField nomeInquilino;
    private javax.swing.JTextField orgEmissorRgInquilino;
    private javax.swing.JTextField profissaoInquilino;
    private javax.swing.JTextField rgInquilino;
    private javax.swing.JButton salvarInquilinoBtn;
    private javax.swing.JTextField telefoneInquilino;
    // End of variables declaration//GEN-END:variables
}
